export const FETCH_SENTENCES = 'FETCH_SENTENCES';
export const SENTENCES_REQUEST = 'SENTENCES_REQUEST';
export const SENTENCES_RESPONSE = 'SENTENCES_RESPONSE';
export const SENTENCES_ERROR = 'SENTENCES_ERROR';
